### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by josephtkim** [jWarbarge/prj-rev-bwfs-dasmoto#5]
**Grade: Exceeds Expectations**

**Summary:** I think that you did an excellent job with your project implementation. The page design and layout seems to closely follow the project specification, and the code is well structured and formatted, and very easily readable. Keep up the great work!

An area of improvement here is to give each important section of the code, both HTML and CSS, a description which provides some detail for other developers to quickly identify them. This becomes even more significant when working with larger code files which can save a lot of time and effort.

As a further challenge, consider adding responsive design to your page. This might take some extra research, but can be a great way to learn and apply important web design concepts. You can take a look at these resources to get started - http://getbootstrap.com/ and https://css-tricks.com/snippets/css/a-guide-to-flexbox/. Based on your work so far, I think you are up for the challenge. Keep up the great work!

**Comment by jWarbarge** [comment]
Thanks for the feedback and the suggestions, and especially thanks for getting to a 2-week late project so quickly!
